name: Thau Landing

on:
  push:
    branches: 
      - master
    paths:
      - '**/*.ts'
      - '**/*.json'
      - '**/*.js'
      - '**/*.yml'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn
          yarn lint

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.4.0
    - name: Setup gcloud
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: quester-263306
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: info
    - name: Build and Push the Thau Landing package
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > key.json
        gcloud auth activate-service-account --key-file=key.json

        yarn
        yarn build

        tar -czvf landing.tar.gz build/
        gsutil cp target/thau-${MVN_VERSION}.jar gs://thau/packages/landing-latest.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup gcloud
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: quester-263306
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: info
    - name: Deploy
      run: |
        echo "${{ secrets.SSH_KEY_THAU_DEV }}" | base64 --decode > .github-ci
        chmod 600 .github-ci
        ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i .github-ci grishin_nikita_gmail_com@thau.quester-app.dev "cd thau-landing && ./deploy.sh"